mysql_user = "root"
mysql_pswd = "123456"
mysql_addr = "localhost:3306"
mysql_name = "tiktok"
minio_endpoint = "0.0.0.0:9000"
minio_access_key_id = "minioadmin"
minio_secret_access_key = "minioadmin"
redis_addr = "localhost:6379"
redis_pswd = "123456"
redis_master_name = "mymaster"
redis_sentinel_addrs = [":1234", ":5678"]
jwt_secret = "f05ad7412aa192ddc121ba50a64e585943b3e6d8fca4a3a19a8eea26e76496a7"
